fragment PostParts on Post {
  __typename
  title
  author {
    ... on Author {
      __typename
      author
      bio
    }
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  date
  draft
  body
}

fragment PageParts on Page {
  __typename
  layout
  title
  body
}

fragment AuthorParts on Author {
  __typename
  author
  bio
}

fragment IssueParts on Issue {
  __typename
  issue
}

fragment DesignationParts on Designation {
  __typename
  designation
  description
}
